Create Database PnP_Sales
Go

Create table PnP_Sales_Master(
ProductID int,
Barcode varchar (250),
ProductName Varchar (250),
Category Varchar (250),
StoreID int,
StoreName Varchar (250),
Province Varchar (250),
CashierName Varchar (250),
SaleDate DATETIME,
Quantity int,
UnitPrice decimal(18,2),
TotalAmount decimal(18,2)
)
insert into PnP_Sales_Master
select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032136184_pnp_sales_2025_01]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032148926_pnp_sales_2025_02]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032159369_pnp_sales_2025_03]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032170316_pnp_sales_2025_04]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032179739_pnp_sales_2025_05]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032189879_pnp_sales_2025_06]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032202072_pnp_sales_2025_07]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032214258_pnp_sales_2025_08]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032224900_pnp_sales_2025_09]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032236969_pnp_sales_2025_10]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032108507_pnp_sales_2025_11]
  union all
  select [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Sales].[dbo].[1772032261154_pnp_sales_2025_12];



